# Generated by Django 6.0.1 on 2026-01-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
